os: osx

language: ruby
rvm:
  - 2.6.3

stages:
  - mac

jobs:
  include:
    - stage: mac
      name: One-Click Installer
      script:
        - sh -c "$(curl -fsSL https://raw.githubusercontent.com/socheatsok78/.next/master/install.sh)"
